#!/bin/bash
# Build script for building and pushing the Docker image

set -e

VERSION=0.2

docker build server \
	--squash \
    --tag gencore/btw-server:$VERSION \
    --tag gencore/btw-server:latest \
    --build-arg VERSION=$VERSION

#docker push gencore/btw-server:$VERSION
#docker push gencore/btw-server:latest